name: Sync labels
on:
  workflow_dispatch:

jobs:
  sync:
    name: Run EndBug/label-sync
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: EndBug/label-sync@v2
        with:
          config-file: 'https://raw.githubusercontent.com/EndBug/labels/main/labels.yml'
